"""
Atelier — AI Creative Director Agent
Hermes Agent Creative Hackathon (Creative Edition)

Main orchestrator: input → analysis → visual → narrative → TTS → output
"""

import argparse
import json
import os
import sys
import uuid
from datetime import datetime

from prompts import ANALYSIS_PROMPT, NARRATIVE_PROMPT
from memory import load_memory, save_session, get_preferences
from visual import generate_visual
from assemble import generate_session_page


def generate_tts(text, output_path):
    """Generate TTS audio from manifesto text using gTTS."""
    try:
        from gtts import gTTS
        tts = gTTS(text=text, lang="en", slow=False)
        tts.save(output_path)
        return output_path
    except Exception as e:
        print(f"[Atelier] TTS failed: {e}")
        return None


def get_kimi_client():
    """Initialize Kimi/OpenRouter client."""
    from openai import OpenAI

    # Try direct Kimi API first, fall back to OpenRouter
    api_key = os.getenv("MOONSHOT_API_KEY") or os.getenv("KIMI_API_KEY")
    if api_key:
        return OpenAI(api_key=api_key, base_url="https://api.moonshot.ai/v1")

    api_key = os.getenv("OPENROUTER_API_KEY")
    if api_key:
        return OpenAI(
            api_key=api_key,
            base_url="https://openrouter.ai/api/v1",
            default_headers={"HTTP-Referer": "https://atelier.ko4lax.dev"},
        )

    print("Error: Set MOONSHOT_API_KEY, KIMI_API_KEY, or OPENROUTER_API_KEY")
    sys.exit(1)


def kimi_call(client, system_prompt, user_content, model="kimi-k2.5"):
    """Call Kimi K2.5 and return the response text."""
    response = client.chat.completions.create(
        model=model,
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_content},
        ],
        temperature=0.6,
        max_tokens=2048,
        extra_body={"thinking": {"type": "disabled"}},
    )
    return response.choices[0].message.content


def analyze_brief(client, brief, memory_prefs=None):
    """Step 1: Analyze user brief into structured creative direction."""
    memory_context = ""
    if memory_prefs:
        memory_context = f"\n\nUser's aesthetic preferences from past sessions:\n{json.dumps(memory_prefs, indent=2)}\nAdjust your analysis to lean toward these preferences where appropriate."

    user_content = f"Brief: {brief}{memory_context}"
    raw = kimi_call(client, ANALYSIS_PROMPT, user_content)

    # Parse JSON from response (handle markdown code blocks)
    text = raw.strip()
    if text.startswith("```"):
        text = text.split("\n", 1)[1].rsplit("```", 1)[0].strip()

    try:
        return json.loads(text)
    except json.JSONDecodeError:
        # Fallback: return raw text wrapped in minimal structure
        return {
            "brand_personality": "creative",
            "visual_direction": "balanced",
            "palette": {"primary_hue": 210, "saturation": 50, "brightness": 80},
            "complexity": 0.5,
            "energy": 0.5,
            "raw_analysis": raw,
        }


def generate_narrative(client, analysis, visual_description):
    """Step 2: Generate brand narrative, taglines, and rationale."""
    user_content = (
        f"Brand analysis:\n{json.dumps(analysis, indent=2)}\n\n"
        f"Visual description:\n{visual_description}"
    )
    raw = kimi_call(client, NARRATIVE_PROMPT, user_content)

    text = raw.strip()
    if text.startswith("```"):
        text = text.split("\n", 1)[1].rsplit("```", 1)[0].strip()

    try:
        return json.loads(text)
    except json.JSONDecodeError:
        return {
            "taglines": [raw[:100]],
            "brand_story": raw,
            "visual_rationale": "Generated by Atelier",
            "manifesto": raw,
        }


def run_atelier(brief, user_id="default", session_id=None):
    """Run the full Atelier pipeline."""
    if session_id is None:
        session_id = datetime.now().strftime("%Y%m%d_%H%M%S") + "_" + uuid.uuid4().hex[:6]

    output_dir = os.path.join(os.path.dirname(__file__), "..", "output", session_id)
    os.makedirs(output_dir, exist_ok=True)

    print(f"[Atelier] Session: {session_id}")
    print(f"[Atelier] Output: {output_dir}")

    # Load memory
    print("[Atelier] Loading memory...")
    prefs = get_preferences(user_id)

    # Init client
    print("[Atelier] Connecting to Kimi...")
    client = get_kimi_client()

    # Step 1: Analyze
    print("[Atelier] Analyzing brief...")
    analysis = analyze_brief(client, brief, prefs)
    print(f"[Atelier] Personality: {analysis.get('brand_personality', '?')}")

    # Step 2: Generate visuals
    print("[Atelier] Generating visuals...")
    visual_info = generate_visual(analysis, output_dir)
    print(f"[Atelier] Visual generated: {visual_info.get('file', '?')}")

    # Step 3: Generate narrative
    print("[Atelier] Generating narrative...")
    narrative = generate_narrative(client, analysis, visual_info.get("description", ""))
    print(f"[Atelier] Taglines: {len(narrative.get('taglines', []))}")

    # Step 4: TTS narration
    print("[Atelier] Generating TTS narration...")
    mp3_path = os.path.join(output_dir, "manifesto.mp3")
    tts_result = generate_tts(narrative.get("manifesto", ""), mp3_path)
    if tts_result:
        print(f"[Atelier] TTS saved: {mp3_path}")

    # Save outputs
    with open(os.path.join(output_dir, "analysis.json"), "w") as f:
        json.dump(analysis, f, indent=2)
    with open(os.path.join(output_dir, "narrative.json"), "w") as f:
        json.dump(narrative, f, indent=2)
    with open(os.path.join(output_dir, "palette.json"), "w") as f:
        json.dump(analysis.get("palette", {}), f, indent=2)

    # Step 6: Assemble full session page (handles webroot sync)
    print("[Atelier] Assembling session page...")
    index_path = generate_session_page(output_dir, session_id)
    print(f"[Atelier] Session page: {index_path}")

    # Save to memory
    print("[Atelier] Saving to memory...")
    save_session(user_id, {
        "session_id": session_id,
        "date": datetime.now().isoformat(),
        "brief": brief,
        "analysis": analysis,
        "narrative": narrative,
    })

    print(f"\n[Atelier] Done! Output at: {output_dir}")
    print(f"[Atelier] View full brand guide: https://atelier.ko4lax.dev/{session_id}/index.html")
    print(f"[Atelier] View visual: https://atelier.ko4lax.dev/{session_id}/visual.html")

    return {
        "session_id": session_id,
        "output_dir": output_dir,
        "analysis": analysis,
        "narrative": narrative,
        "visual": visual_info,
    }


def main():
    parser = argparse.ArgumentParser(description="Atelier — AI Creative Director")
    parser.add_argument("--brief", "-b", required=True, help="Brand brief or description")
    parser.add_argument("--user", "-u", default="default", help="User ID for memory")
    parser.add_argument("--session", "-s", default=None, help="Session ID (auto-generated if omitted)")
    args = parser.parse_args()

    run_atelier(args.brief, args.user, args.session)


if __name__ == "__main__":
    main()
